# Generated by Django 4.2.7 on 2023-12-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="description",
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="thing",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="thing",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
